language:
  - php

branches:
  except:
    - /^feature.*$/

git:
  depth: 1

php:
  - 5.5

before_install:
  - /home/travis/.phpenv/versions/5.5/bin/composer self-update

install:
  - composer self-update
  - composer install

script:
  - find ./ -name "*.php" | fgrep -v "/vendor/" | xargs -l1 -P8 php -l > /dev/null 
  - vendor/bin/phpunit $TRAVIS_BUILD_DIR/tests
  - vendor/bin/phpcs -n --extensions=php --standard=PEAR --ignore="*/vendor/*"

notifications:
  email:
   - y-kobayashi@mediba.jp
